name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Site
      run: |
        hugo -d docs
        sed -i -r 's/featured(.+?)gif/featured.gif/g' docs/index.html
        sed -i -r 's/class="btn-group flex-wrap"/class="btn-group flex-wrap" style="flex-wrap: unset !important; !important;"/g' docs/index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: deploy
        publish_dir: ./docs
